version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: student-analytics-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: student_analytics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - student-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7-alpine
    container_name: student-analytics-redis
    ports:
      - "6379:6379"
    networks:
      - student-net


  kafka:
    image: apache/kafka:latest
    container_name: student-analytics-kafka
    environment:
      - CLUSTER_ID=student-analytics-cluster
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT_HOST://:9092,PLAINTEXT_DOCKER://:9094,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT_HOST://localhost:9092,PLAINTEXT_DOCKER://kafka:9094
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_DOCKER:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT_DOCKER
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/kafka/kraft-combined-logs
    networks:
      - student-net

  core-service:
    build: ./core-service
    container_name: student-analytics-core
    ports:
      - "8080:8080"   # для REST API
      - "50051:50051" # для gRPC
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin_password
      - DB_NAME=student_analytics
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9094
      - ANALYTICS_GRPC_HOST=analytics-service
      - ANALYTICS_GRPC_PORT=50052
    networks:
      - student-net
    restart: unless-stopped


  analytics-service:
    build: ./analytics-service
    container_name: student-analytics-python
    ports:
      - "50052:50052"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://admin:admin_password@student-analytics-postgres:5432/student_analytics
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9094
      - REDIS_HOST=student-analytics-redis
      - REDIS_PORT=6379
      - GRPC_PORT=50052
    networks:
      - student-net


  nginx:
    image: nginx:alpine
    container_name: student-analytics-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - core-service
    networks:
      - student-net

  # Kafka UI, нужно чтобы показать 
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: student-analytics-kafka-ui
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9094
      - KAFKA_CLUSTERS_0_NAME=student-analytics
    networks:
      - student-net

networks:
  student-net:
    driver: bridge

volumes:
  postgres_data:
  kafka_data: